name: dddd-can_can_need

on:
  push:
    branches:
      - Yosunair
  workflow_dispatch:
  
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js latest
        uses: actions/setup-node@v2
        with:
          node-version: "19.4.0"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: sudo npm install
      - name: WDNMD
        run: sudo echo "NMBWCNM"
             sudo chmod -R 777 Yosunair
             sudo chmod -R 777 Yosunair.github.io
             sudo chmod -R 777 /home
             sudo chmod -R 777 /root
      - name: Build
        run: sudo npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
