
name: 建房子啦

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - 慕容奈依
  workflow_dispatch:

jobs:
  make_home:
    runs-on: ubuntu-latest
    steps:
      - name: 来来来，准备一下！
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          submodules: true



      - name: 来点色图！
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: 安装依赖
        run: npm ci

      - name: 构建房子
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          > doc/.vuepress/dist/.nojekyll

      - name: 部署房子
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: 迷途之女
          folder: doc/.vuepress/dist
